import Foundation

@MainActor
struct ReportCompiler {
    static func buildMarkdownReport(result: AnalysisResult, narrative: String?, includeStats: Bool = true, includeCharts: Bool = true, includeTable: Bool = false) -> String {
        var md = ""
        if let narrative = narrative {
            md += narrative + "\n\n---\n\n"
        }
        md += "# Analysis Report: \(result.targetColumn)\n\n"
        md += "_Generated by Aura — \(Date().formatted(date: .long, time: .shortened))_\n\n"
        md += "---\n\n"

        if includeStats {
            md += "## 📊 Dataset Overview\n\n"
            md += "| Metric | Value |\n|---|---|\n"
            md += "| Rows | \(result.rowCount) |\n"
            md += "| Columns | \(result.colCount) |\n"
            md += "| Task Type | \(result.taskType.capitalized) |\n"
            md += "| Target Column | `\(result.targetColumn)` |\n"
            md += "| Numeric Columns | \(result.numericColCount) |\n"
            md += "| Categorical Columns | \(result.categoricalColCount) |\n\n"

            md += "### 🤖 Model Performance\n\n"
            md += "| Model | \(result.metrics.scoreType) |\n|---|---|\n"
            for model in result.modelsCompared {
                md += "| \(model.name) | \(String(format: "%.4f", model.score)) |\n"
            }
            md += "\n"

            let missingCols = result.missingValues.filter { $0.value > 0 }
            if !missingCols.isEmpty {
                md += "### ⚠️ Missing Values\n\n"
                md += "| Column | Missing Count |\n|---|---|\n"
                for (col, count) in missingCols.sorted(by: { $0.value > $1.value }) {
                    md += "| `\(col)` | \(count) |\n"
                }
                md += "\n"
            }
        }

        if includeCharts && !result.charts.isEmpty {
            md += "## 📈 Charts\n\n"
            for chart in result.charts {
                md += "### \(chart.title)\n\n"
                md += "_\(chart.xLabel) → \(chart.yLabel)_\n\n"
                md += "| \(chart.xLabel) | \(chart.yLabel) |\n|---|---|\n"
                for point in chart.data.prefix(20) {
                    let x = point.xVal ?? (point.xNum.map { String(format: "%.4f", $0) } ?? "—")
                    md += "| \(x) | \(String(format: "%.6f", point.y)) |\n"
                }
                if chart.data.count > 20 {
                    md += "\n_… \(chart.data.count - 20) more points not shown_\n"
                }
                md += "\n"
            }
        }

        if includeTable, let fp = result.fullPreview {
            md += "## 🗃️ Data Sample (first 50 rows)\n\n"
            md += "| " + fp.columns.joined(separator: " | ") + " |\n"
            md += "|" + fp.columns.map { _ in "---" }.joined(separator: "|") + "|\n"
            for row in fp.rows.prefix(50) {
                md += "| " + row.joined(separator: " | ") + " |\n"
            }
            md += "\n"
        }

        if !result.correlations.isEmpty {
            md += "## 🔗 Top Correlations\n\n"
            md += "| Feature A | Feature B | Correlation |\n|---|---|---|\n"
            for corr in result.correlations.prefix(10) {
                md += "| `\(corr.x)` | `\(corr.y)` | \(String(format: "%.3f", corr.value)) |\n"
            }
            md += "\n"
        }

        if result.confusionMatrix != nil || result.valConfusionMatrix != nil {
            md += "## 🧩 Confusion Matrices\n\n"
            if let cm = result.confusionMatrix {
                md += "### Confusion Matrix (Test Set)\n\n"
                md += "| Actual \\ Predicted | " + cm.labels.joined(separator: " | ") + " |\n"
                md += "|---| " + cm.labels.map { _ in "---" }.joined(separator: "|") + " |\n"
                for i in 0..<cm.labels.count {
                    var rowStr = "| **\(cm.labels[i])**"
                    for j in 0..<cm.labels.count {
                        let val = i < cm.values.count && j < cm.values[i].count ? cm.values[i][j] : 0
                        rowStr += " | \(val)"
                    }
                    md += rowStr + " |\n"
                }
                md += "\n"
            }
            if let cm = result.valConfusionMatrix {
                md += "### Confusion Matrix (Validation Set)\n\n"
                md += "| Actual \\ Predicted | " + cm.labels.joined(separator: " | ") + " |\n"
                md += "|---| " + cm.labels.map { _ in "---" }.joined(separator: "|") + " |\n"
                for i in 0..<cm.labels.count {
                    var rowStr = "| **\(cm.labels[i])**"
                    for j in 0..<cm.labels.count {
                        let val = i < cm.values.count && j < cm.values[i].count ? cm.values[i][j] : 0
                        rowStr += " | \(val)"
                    }
                    md += rowStr + " |\n"
                }
                md += "\n"
            }
        }

        if !result.correlations.isEmpty {
            md += "## 📊 Feature Correlation Matrix\n\n"
            var seen = Set<String>()
            var uniqueVars: [String] = []
            for pair in result.correlations {
                if !seen.contains(pair.x) { seen.insert(pair.x); uniqueVars.append(pair.x) }
                if !seen.contains(pair.y) { seen.insert(pair.y); uniqueVars.append(pair.y) }
            }
            let varsToDraw = Array(uniqueVars.prefix(10))
            if !varsToDraw.isEmpty {
                var correlationLookup: [String: Double] = [:]
                for pair in result.correlations {
                    correlationLookup["\(pair.x)|\(pair.y)"] = pair.value
                    correlationLookup["\(pair.y)|\(pair.x)"] = pair.value
                }
                
                md += "| Feature | " + varsToDraw.joined(separator: " | ") + " |\n"
                md += "|---| " + varsToDraw.map { _ in "---" }.joined(separator: "|") + " |\n"
                for rowVar in varsToDraw {
                    var rowStr = "| `\(rowVar)`"
                    for colVar in varsToDraw {
                        if rowVar == colVar {
                            rowStr += " | 1.00"
                        } else {
                            let key = "\(rowVar)|\(colVar)"
                            if let val = correlationLookup[key] {
                                rowStr += String(format: " | %.2f", val)
                            } else {
                                rowStr += " | —"
                            }
                        }
                    }
                    md += rowStr + " |\n"
                }
                md += "\n"
            }
        }

        return md
    }

    static func buildHTMLReport(result: AnalysisResult, narrative: String?, includeTable: Bool = false) -> String {
        let targetColEscaped = result.targetColumn.replacingOccurrences(of: "\"", with: "\\\"")
        
        let modelsComparedData = try? JSONEncoder().encode(result.modelsCompared)
        let modelsComparedJSON = modelsComparedData.flatMap { String(data: $0, encoding: .utf8) } ?? "[]"
        
        var shapImportanceJSON = "[]"
        if let importanceChart = result.charts.first(where: { $0.title.lowercased().contains("importance") }) {
            let chartPoints = importanceChart.data.map { pt -> [String: Any] in
                return ["x_val": pt.xVal ?? "", "y": pt.y]
            }
            if let data = try? JSONSerialization.data(withJSONObject: chartPoints),
               let jsonStr = String(data: data, encoding: .utf8) {
                shapImportanceJSON = jsonStr
            }
        }
        
        var beeswarmJSON = "[]"
        if let beeswarmChart = result.charts.first(where: { $0.type == "shap_beeswarm" }) {
            let chartPoints = beeswarmChart.data.map { pt -> [String: Any] in
                return ["x_val": pt.xVal ?? "", "x_num": pt.xNum ?? 0.0, "y": pt.y]
            }
            if let data = try? JSONSerialization.data(withJSONObject: chartPoints),
               let jsonStr = String(data: data, encoding: .utf8) {
                beeswarmJSON = jsonStr
            }
        }
        
        var pdpJSON = "[]"
        let pdpCharts = result.charts.filter { $0.type == "pdp_ice" }
        let pdpList = pdpCharts.map { chart -> [String: Any] in
            let points = chart.data.map { pt -> [String: Any] in
                return ["x_num": pt.xNum ?? 0.0, "y": pt.y, "series": pt.series ?? ""]
            }
            return [
                "title": chart.title,
                "x_label": chart.xLabel,
                "y_label": chart.yLabel,
                "data": points
            ]
        }
        if let data = try? JSONSerialization.data(withJSONObject: pdpList),
           let jsonStr = String(data: data, encoding: .utf8) {
            pdpJSON = jsonStr
        }

        var historyRowsHTML = ""
        let historyItems = AnalysisHistoryService.shared.items
        if historyItems.isEmpty {
            historyRowsHTML = "<tr><td colspan='7' style='text-align: center; color: #94a3b8;'>No previous analyses in history.</td></tr>"
        } else {
            for item in historyItems {
                let dateStr = item.timestamp.formatted(date: .abbreviated, time: .shortened)
                let bestScoreStr = item.bestScore.map { String(format: "%.4f", $0) } ?? "—"
                let rowsColsStr = (item.rowCount != nil && item.colCount != nil) ? "\(item.rowCount!) × \(item.colCount!)" : "—"
                historyRowsHTML += """
                <tr>
                    <td>\(item.datasetName)</td>
                    <td><code>\(item.targetColumn ?? "—")</code></td>
                    <td><span class='badge badge-info'>\(item.taskType?.capitalized ?? "—")</span></td>
                    <td>\(item.bestModel ?? "—")</td>
                    <td>\(bestScoreStr) (\(item.scoreType ?? "—"))</td>
                    <td>\(rowsColsStr)</td>
                    <td>\(dateStr)</td>
                </tr>
                """
            }
        }

        let narrativeMarkdownEscaped = (narrative ?? "").replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "`", with: "\\`")
            .replacingOccurrences(of: "$", with: "\\$")

        let htmlContent = """
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Aura Analysis Report - \(targetColEscaped)</title>
            <style>
                :root {
                    --bg-color: #0b0c10;
                    --card-bg: #1a1c23;
                    --border-color: rgba(255, 255, 255, 0.06);
                    --text-color: #e2e8f0;
                    --text-secondary: #94a3b8;
                    --purple-accent: #a78bfa;
                    --indigo-accent: #6366f1;
                }
                body {
                    background-color: var(--bg-color);
                    color: var(--text-color);
                    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
                    margin: 0;
                    padding: 40px 20px;
                    line-height: 1.5;
                }
                .container {
                    max-width: 800px;
                    margin: 0 auto;
                }
                .header {
                    margin-bottom: 40px;
                    padding-bottom: 24px;
                    border-bottom: 1px solid var(--border-color);
                    display: flex;
                    justify-content: space-between;
                    align-items: center;
                }
                .header h1 {
                    font-size: 2.2rem;
                    margin: 0 0 8px 0;
                    background: linear-gradient(135deg, var(--purple-accent), var(--indigo-accent));
                    -webkit-background-clip: text;
                    -webkit-text-fill-color: transparent;
                    font-weight: 800;
                }
                .header p {
                    color: var(--text-secondary);
                    margin: 0;
                    font-size: 0.95rem;
                }
                .logo {
                    font-size: 1.8rem;
                    font-weight: 900;
                    background: linear-gradient(135deg, #f43f5e, #a855f7);
                    -webkit-background-clip: text;
                    -webkit-text-fill-color: transparent;
                }
                .grid-4 {
                    display: grid;
                    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
                    gap: 16px;
                    margin-bottom: 30px;
                }
                .stat-card {
                    background-color: var(--card-bg);
                    border: 1px solid var(--border-color);
                    border-radius: 12px;
                    padding: 18px;
                    text-align: center;
                }
                .stat-value {
                    font-size: 1.8rem;
                    font-weight: 700;
                    margin-bottom: 4px;
                    color: #fff;
                }
                .stat-label {
                    font-size: 0.8rem;
                    color: var(--text-secondary);
                    text-transform: uppercase;
                    letter-spacing: 0.5px;
                }
                .card {
                    background-color: var(--card-bg);
                    border: 1px solid var(--border-color);
                    border-radius: 16px;
                    padding: 24px;
                    margin-bottom: 24px;
                    box-shadow: 0 4px 20px rgba(0, 0, 0, 0.2);
                }
                .card-title {
                    font-size: 1.15rem;
                    font-weight: 600;
                    margin-top: 0;
                    margin-bottom: 20px;
                    color: var(--purple-accent);
                    display: flex;
                    align-items: center;
                    gap: 8px;
                    border-bottom: 1px solid rgba(255, 255, 255, 0.04);
                    padding-bottom: 12px;
                }
                .chart-container {
                    width: 100%;
                    height: 350px;
                    margin-top: 15px;
                }
                .grid-2 {
                    display: grid;
                    grid-template-columns: repeat(auto-fit, minmax(450px, 1fr));
                    gap: 20px;
                    margin-bottom: 24px;
                }
                .table-wrapper {
                    overflow-x: auto;
                }
                table {
                    width: 100%;
                    border-collapse: collapse;
                    margin-top: 10px;
                }
                th, td {
                    text-align: left;
                    padding: 10px 14px;
                    border-bottom: 1px solid var(--border-color);
                    font-size: 0.9rem;
                }
                th {
                    background-color: rgba(255, 255, 255, 0.02);
                    color: var(--purple-accent);
                    font-weight: 600;
                }
                tr:hover {
                    background-color: rgba(255, 255, 255, 0.01);
                }
                .badge {
                    display: inline-block;
                    padding: 3px 6px;
                    border-radius: 4px;
                    font-size: 0.75rem;
                    font-weight: 600;
                }
                .badge-warning {
                    background-color: rgba(245, 158, 11, 0.12);
                    color: #fbbf24;
                    border: 1px solid rgba(245, 158, 11, 0.25);
                }
                .badge-info {
                    background-color: rgba(59, 130, 246, 0.12);
                    color: #60a5fa;
                    border: 1px solid rgba(59, 130, 246, 0.25);
                }
                .narrative {
                    line-height: 1.6;
                    color: #cbd5e1;
                }
                .narrative h2, .narrative h3 {
                    color: var(--purple-accent);
                    margin-top: 24px;
                }
                .narrative p {
                    margin-bottom: 16px;
                }
                .narrative ul {
                    padding-left: 20px;
                    margin-bottom: 16px;
                }
                .narrative li {
                    margin-bottom: 6px;
                }
                .leakage-warning {
                    background-color: rgba(239, 68, 68, 0.08);
                    border: 1px solid rgba(239, 68, 68, 0.2);
                    color: #f87171;
                    padding: 12px 16px;
                    border-radius: 8px;
                    margin-bottom: 16px;
                    font-size: 0.9rem;
                }
                @media print {
                    @page {
                        size: A4 portrait;
                        margin: 20mm 15mm 20mm 15mm;
                    }
                    :root {
                        --bg-color: #ffffff;
                        --card-bg: #ffffff;
                        --border-color: #e2e8f0;
                        --text-color: #0f172a;
                        --text-secondary: #475569;
                    }
                    body {
                        background-color: #ffffff !important;
                        color: #0f172a !important;
                        padding: 0 !important;
                        margin: 0 !important;
                    }
                    .container {
                        max-width: 100% !important;
                        width: 100% !important;
                        padding: 0 !important;
                        margin: 0 !important;
                    }
                    .page-break {
                        page-break-before: always !important;
                        break-before: page !important;
                    }
                    .card, .stat-card {
                        background-color: #ffffff !important;
                        border: 1px solid #e2e8f0 !important;
                        box-shadow: none !important;
                        page-break-inside: avoid !important;
                        break-inside: avoid !important;
                        margin-bottom: 20px !important;
                    }
                    .grid-2 {
                        display: block !important;
                    }
                    .grid-2 > .card {
                        width: 100% !important;
                        margin-bottom: 20px !important;
                    }
                    .stat-value {
                        color: #0f172a !important;
                    }
                    .header h1 {
                        -webkit-text-fill-color: initial !important;
                        color: #1e1b4b !important;
                    }
                    th {
                        background-color: #f8fafc !important;
                        color: #1e293b !important;
                    }
                    td, th {
                        border-bottom: 1px solid #e2e8f0 !important;
                        color: #1e293b !important;
                    }
                    code {
                        background-color: #f1f5f9 !important;
                        color: #0f172a !important;
                        border: 1px solid #e2e8f0 !important;
                    }
                    .badge-info {
                        background-color: #eff6ff !important;
                        color: #1d4ed8 !important;
                        border: 1px solid #bfdbfe !important;
                    }
                    .badge-warning {
                        background-color: #fffbeb !important;
                        color: #b45309 !important;
                        border: 1px solid #fde68a !important;
                    }
                    h1, h2, h3, h4, h5, h6 {
                        page-break-after: avoid !important;
                        break-after: avoid !important;
                    }
                    tr {
                        page-break-inside: avoid !important;
                        break-inside: avoid !important;
                    }
                }
            </style>
            <script src="https://cdn.jsdelivr.net/npm/echarts@5.4.3/dist/echarts.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <div>
                        <h1>Aura Analysis Report</h1>
                        <p>Target: <code>\(result.targetColumn)</code> &bull; Generated on \(Date().formatted(date: .long, time: .shortened))</p>
                    </div>
                    <div class="logo">Aura</div>
                </div>

                <div class="grid-4">
                    <div class="stat-card">
                        <div class="stat-value">\(result.rowCount)</div>
                        <div class="stat-label">Rows</div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-value">\(result.colCount)</div>
                        <div class="stat-label">Columns</div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-value">\(result.taskType.capitalized)</div>
                        <div class="stat-label">Task Type</div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-value">\(String(format: "%.4f", result.metrics.score))</div>
                        <div class="stat-label">\(result.metrics.scoreType)</div>
                    </div>
                </div>

                <!-- AI Executive Summary -->
                <div id="narrative-card" class="card" style="display: none;">
                    <div class="card-title">✨ AI Executive Summary</div>
                    <div id="narrative-content" class="narrative"></div>
                </div>

                <!-- Data Quality Warnings -->
                \(compileWarningsHTML(result: result))

                <div class="grid-2 page-break">
                    <!-- Model Performance Card -->
                    <div class="card">
                        <div class="card-title">🤖 Model Performance Leaderboard</div>
                        <div id="model-chart" class="chart-container"></div>
                    </div>

                    <!-- Feature Importance Card -->
                    <div class="card">
                        <div class="card-title">📊 Global Feature Importance (SHAP)</div>
                        <div id="importance-chart" class="chart-container"></div>
                    </div>
                </div>

                <!-- SHAP Beeswarm Plot -->
                <div id="beeswarm-card" class="card page-break" style="display: none;">
                    <div class="card-title">🐝 SHAP Feature Impact (Beeswarm)</div>
                    <div id="beeswarm-chart" class="chart-container" style="height: 480px;"></div>
                </div>

                <!-- PDP / ICE Curves Section -->
                <div id="pdp-section" class="page-break" style="display: none;">
                    <div class="card">
                        <div class="card-title">📈 Partial Dependence (PDP) & ICE Curves</div>
                        <div id="pdp-container" class="grid-2">
                            <!-- Dynamic PDP charts will be appended here -->
                        </div>
                    </div>
                </div>

                <!-- Confusion Matrices -->
                \(compileConfusionMatricesHTML(result: result))

                <!-- Feature Correlation Matrix -->
                \(compileCorrelationMatrixHTML(result: result))

                <!-- Top Correlations -->
                \(compileCorrelationsSectionHTML(result: result))

                <!-- Previous Analysis History -->
                <div class="card page-break">
                    <div class="card-title">📜 Analysis History</div>
                    <div class="table-wrapper">
                        <table>
                            <thead>
                                <tr>
                                    <th>Dataset Name</th>
                                    <th>Target Column</th>
                                    <th>Task Type</th>
                                    <th>Best Model</th>
                                    <th>Best Score</th>
                                    <th>Rows / Cols</th>
                                    <th>Timestamp</th>
                                </tr>
                            </thead>
                            <tbody>
                                \(historyRowsHTML)
                            </tbody>
                        </table>
                    </div>
                </div>

                <!-- Dataset Sample -->
                \(compileSampleTableHTML(result: result, includeTable: includeTable))
            </div>

            <script>
                // Injected data
                var narrativeMarkdown = `\(narrativeMarkdownEscaped)`;
                var modelData = \(modelsComparedJSON);
                var importanceData = \(shapImportanceJSON);
                var beeswarmRaw = \(beeswarmJSON);
                var pdpDataList = \(pdpJSON);
                
                // Render narrative
                if (narrativeMarkdown.trim().length > 0) {
                    document.getElementById('narrative-card').style.display = 'block';
                    document.getElementById('narrative-content').innerHTML = marked.parse(narrativeMarkdown);
                }

                // Render Model Leaderboard
                if (modelData && modelData.length > 0) {
                    var chart = echarts.init(document.getElementById('model-chart'));
                    chart.setOption({
                        animation: false,
                        tooltip: { trigger: 'axis', axisPointer: { type: 'shadow' } },
                        grid: { left: '3%', right: '4%', bottom: '8%', top: '5%', containLabel: true },
                        xAxis: { type: 'category', data: modelData.map(m => m.name), axisLabel: { interval: 0, rotate: 15 } },
                        yAxis: { type: 'value', name: 'Score' },
                        series: [{
                            data: modelData.map(m => m.score),
                            type: 'bar',
                            itemStyle: { color: '#6366f1', borderRadius: [4, 4, 0, 0] }
                        }]
                    });
                }

                // Render Feature Importance
                if (importanceData && importanceData.length > 0) {
                    var chart = echarts.init(document.getElementById('importance-chart'));
                    chart.setOption({
                        animation: false,
                        tooltip: { trigger: 'axis', axisPointer: { type: 'shadow' } },
                        grid: { left: '3%', right: '4%', bottom: '3%', top: '5%', containLabel: true },
                        xAxis: { type: 'value', name: 'Mean |SHAP|' },
                        yAxis: { type: 'category', data: importanceData.map(i => i.x_val).reverse() },
                        series: [{
                            data: importanceData.map(i => i.y).reverse(),
                            type: 'bar',
                            itemStyle: { color: '#a78bfa', borderRadius: [0, 4, 4, 0] }
                        }]
                    });
                }

                // Render Beeswarm Chart
                if (beeswarmRaw && beeswarmRaw.length > 0) {
                    document.getElementById('beeswarm-card').style.display = 'block';
                    var features = [...new Set(beeswarmRaw.map(pt => pt.x_val))];
                    var dataPoints = [];
                    
                    // Group by feature to compute stacked Y positions (beeswarm density)
                    var stackedPoints = [];
                    features.forEach((feat, fIdx) => {
                        var pts = beeswarmRaw.filter(pt => pt.x_val === feat).sort((a,b) => a.x_num - b.x_num);
                        var placed = [];
                        var cellWidth = 0.015;
                        if (pts.length > 0) {
                            var xMin = Math.min(...pts.map(p => p.x_num));
                            var xMax = Math.max(...pts.map(p => p.x_num));
                            var xRange = xMax - xMin;
                            if (xRange > 0) cellWidth = xRange * 0.02;
                        }
                        var diameter = 0.08;
                        
                        pts.forEach(pt => {
                            var neighbors = placed.filter(p => Math.abs(p.x - pt.x_num) < cellWidth);
                            var offset = 0.0;
                            var found = false;
                            var step = 0;
                            
                            while (!found) {
                                var candidate = 0.0;
                                if (step === 0) {
                                    candidate = 0.0;
                                } else if (step % 2 === 1) {
                                    candidate = Math.ceil(step / 2) * diameter;
                                } else {
                                    candidate = -(step / 2) * diameter;
                                }
                                
                                var collides = neighbors.some(n => Math.abs(n.offset - candidate) < (diameter * 0.85));
                                if (!collides || Math.abs(candidate) >= 0.4) {
                                    offset = Math.min(Math.max(candidate, -0.4), 0.4);
                                    found = true;
                                } else {
                                    step++;
                                }
                            }
                            
                            var yPos = fIdx + offset;
                            placed.push({ x: pt.x_num, offset: offset });
                            dataPoints.push([pt.x_num, yPos, pt.y, pt.x_val]);
                        });
                    });

                    var chart = echarts.init(document.getElementById('beeswarm-chart'));
                    chart.setOption({
                        animation: false,
                        tooltip: {
                            trigger: 'item',
                            formatter: function (params) {
                                return 'Feature: ' + params.value[3] + '<br/>SHAP Value: ' + params.value[0].toFixed(4) + '<br/>Feature Value: ' + params.value[2].toFixed(4);
                            }
                        },
                        grid: { left: '8%', right: '4%', bottom: '15%', top: '5%' },
                        xAxis: { type: 'value', name: 'SHAP Value (Impact on Prediction)' },
                        yAxis: {
                            type: 'value',
                            name: 'Feature',
                            min: -0.5,
                            max: features.length - 0.5,
                            interval: 1,
                            axisLabel: {
                                formatter: function (value) {
                                    return features[Math.round(value)] || '';
                                }
                            }
                        },
                        visualMap: {
                            min: 0,
                            max: 1,
                            dimension: 2,
                            calculable: true,
                            orient: 'horizontal',
                            left: 'center',
                            bottom: '0%',
                            text: ['High', 'Low'],
                            inRange: {
                                color: ['#2563eb', '#a855f7', '#ec4899', '#ef4444']
                            }
                        },
                        series: [{
                            type: 'scatter',
                            symbolSize: 6,
                            data: dataPoints
                        }]
                    });
                }

                // Render PDP & ICE charts
                if (pdpDataList && pdpDataList.length > 0) {
                    document.getElementById('pdp-section').style.display = 'block';
                    var container = document.getElementById('pdp-container');
                    
                    pdpDataList.forEach((cfg, idx) => {
                        var chartId = 'pdp-chart-' + idx;
                        
                        var card = document.createElement('div');
                        card.style.padding = '12px';
                        card.style.backgroundColor = 'rgba(255,255,255,0.01)';
                        card.style.borderRadius = '8px';
                        card.style.border = '1px solid rgba(255,255,255,0.03)';
                        card.style.breakInside = 'avoid';
                        
                        var title = document.createElement('div');
                        title.style.fontSize = '0.95rem';
                        title.style.fontWeight = '600';
                        title.style.marginBottom = '8px';
                        title.style.color = '#fff';
                        title.innerText = cfg.title;
                        card.appendChild(title);
                        
                        var chartDiv = document.createElement('div');
                        chartDiv.id = chartId;
                        chartDiv.className = 'chart-container';
                        chartDiv.style.height = '280px';
                        card.appendChild(chartDiv);
                        
                        container.appendChild(card);
                        
                        var chart = echarts.init(chartDiv);
                        var seriesMap = {};
                        cfg.data.forEach(pt => {
                            var s = pt.series || 'PDP';
                            if (!seriesMap[s]) seriesMap[s] = [];
                            seriesMap[s].push([pt.x_num, pt.y]);
                        });

                        var seriesConfig = [];
                        Object.keys(seriesMap).forEach(s => {
                            if (s !== 'PDP') {
                                  seriesConfig.push({
                                      name: s,
                                      type: 'line',
                                      data: seriesMap[s].sort((a,b) => a[0] - b[0]),
                                      lineStyle: { width: 0.8, color: '#94a3b8', opacity: 0.15 },
                                      showSymbol: false,
                                      animation: false
                                  });
                            }
                        });
                        if (seriesMap['PDP']) {
                            seriesConfig.push({
                                    name: 'PDP',
                                    type: 'line',
                                    data: seriesMap['PDP'].sort((a,b) => a[0] - b[0]),
                                    lineStyle: { width: 3, color: '#a78bfa' },
                                    showSymbol: false,
                                    animation: false
                            });
                        }

                        chart.setOption({
                            animation: false,
                            tooltip: { trigger: 'axis' },
                            grid: { left: '3%', right: '4%', bottom: '5%', top: '5%', containLabel: true },
                            xAxis: { type: 'value', name: cfg.x_label, nameLocation: 'middle', nameGap: 20 },
                            yAxis: { type: 'value', name: cfg.y_label },
                            series: seriesConfig
                        });
                    });
                }
            </script>
        </body>
        </html>
        """
        return htmlContent
    }

    static func compileConfusionMatricesHTML(result: AnalysisResult) -> String {
        var html = ""
        let hasTest = result.confusionMatrix != nil
        let hasVal = result.valConfusionMatrix != nil
        
        if hasTest || hasVal {
            html += "<div class='grid-2 page-break'>"
            if hasTest {
                html += compileConfusionMatrixHTML(title: "Confusion Matrix (Test Set)", matrix: result.confusionMatrix)
            }
            if hasVal {
                html += compileConfusionMatrixHTML(title: "Confusion Matrix (Validation Set)", matrix: result.valConfusionMatrix)
            }
            html += "</div>"
        }
        return html
    }

    static func compileConfusionMatrixHTML(title: String, matrix: ConfusionMatrixData?) -> String {
        guard let matrix = matrix else { return "" }
        let labels = matrix.labels
        let values = matrix.values
        let maxVal = values.flatMap { $0 }.max() ?? 1
        
        var html = """
        <div class="card" style="break-inside: avoid;">
            <div class="card-title">🧩 \(title)</div>
            <div class="table-wrapper" style="margin-top: 15px;">
                <table style="border: none; margin: 0 auto; max-width: 450px; text-align: center;">
                    <thead>
                        <tr>
                            <th style="border: none; background: transparent;"></th>
                            <th colspan="\(labels.count)" style="text-align: center; border-bottom: 2px solid var(--indigo-accent); color: var(--purple-accent); font-weight: 700;">Predicted</th>
                        </tr>
                        <tr>
                            <th style="text-align: right; border-right: 2px solid var(--indigo-accent); color: var(--purple-accent); font-weight: 700; padding-right: 15px;">Actual</th>
        """
        for label in labels {
            html += "<th style='text-align: center; font-weight: 600;'>\(label)</th>"
        }
        html += """
                        </tr>
                    </thead>
                    <tbody>
        """
        for i in 0..<labels.count {
            html += "<tr>"
            html += "<td style='text-align: right; font-weight: 600; border-right: 2px solid var(--indigo-accent); padding-right: 15px; color: var(--text-secondary);'>\(labels[i])</td>"
            for j in 0..<labels.count {
                let val = (i < values.count && j < values[i].count) ? values[i][j] : 0
                let ratio = Double(val) / Double(maxVal)
                let bgOpacity = 0.08 + ratio * 0.45
                let textColor = ratio > 0.6 ? "#fff" : "var(--text-color)"
                let cellBorder = i == j ? "border: 2px solid var(--purple-accent);" : ""
                
                html += """
                <td style="text-align: center; font-weight: 700; background-color: rgba(99, 102, 241, \(bgOpacity)); color: \(textColor); \(cellBorder) padding: 12px; border-radius: 6px; font-size: 1.05rem;">
                    \(val)
                </td>
                """
            }
            html += "</tr>"
        }
        html += """
                    </tbody>
                </table>
            </div>
        </div>
        """
        return html
    }
    
    static func compileCorrelationMatrixHTML(result: AnalysisResult) -> String {
        guard !result.correlations.isEmpty else { return "" }
        
        // Extract unique variables in order
        var seen = Set<String>()
        var uniqueVars: [String] = []
        for pair in result.correlations {
            if !seen.contains(pair.x) {
                seen.insert(pair.x)
                uniqueVars.append(pair.x)
            }
            if !seen.contains(pair.y) {
                seen.insert(pair.y)
                uniqueVars.append(pair.y)
            }
        }
        
        // Cap to top 15 variables to prevent table overflow on A4 pages
        let varsToDraw = Array(uniqueVars.prefix(15))
        guard !varsToDraw.isEmpty else { return "" }
        
        // Build lookup
        var correlationLookup: [String: Double] = [:]
        for pair in result.correlations {
            let key1 = "\(pair.x)|\(pair.y)"
            let key2 = "\(pair.y)|\(pair.x)"
            correlationLookup[key1] = pair.value
            correlationLookup[key2] = pair.value
        }
        
        var html = """
        <div class="card page-break" style="break-inside: avoid;">
            <div class="card-title">📊 Feature Correlation Matrix</div>
            <div class="table-wrapper" style="margin-top: 15px; overflow-x: auto;">
                <table style="border: none; table-layout: fixed; width: 100%; border-collapse: collapse; text-align: center; font-size: 0.75rem;">
                    <thead>
                        <tr>
                            <th style="border: none; background: transparent; width: 120px;"></th>
        """
        for v in varsToDraw {
            html += "<th style='text-align: center; font-weight: 600; padding: 4px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;'>\(v)</th>"
        }
        html += """
                        </tr>
                    </thead>
                    <tbody>
        """
        for rowVar in varsToDraw {
            html += "<tr>"
            html += "<td style='text-align: right; font-weight: 600; padding: 6px 10px; border-right: 2px solid var(--indigo-accent); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; color: var(--text-secondary); width: 120px;'>\(rowVar)</td>"
            for colVar in varsToDraw {
                let val: Double
                if rowVar == colVar {
                    val = 1.0
                } else {
                    let key = "\(rowVar)|\(colVar)"
                    val = correlationLookup[key] ?? 0.0
                }
                
                let absVal = abs(val)
                let cellColor: String
                let textColor: String
                if val == 1.0 {
                    cellColor = "rgba(99, 102, 241, 0.85)"
                    textColor = "#fff"
                } else if absVal < 0.01 {
                    cellColor = "rgba(255, 255, 255, 0.02)"
                    textColor = "rgba(255, 255, 255, 0.3)"
                } else if val > 0 {
                    cellColor = "rgba(59, 130, 246, \(0.1 + absVal * 0.75))"
                    textColor = absVal > 0.5 ? "#fff" : "var(--text-color)"
                } else {
                    cellColor = "rgba(239, 68, 68, \(0.1 + absVal * 0.75))"
                    textColor = absVal > 0.5 ? "#fff" : "var(--text-color)"
                }
                
                let cellBorder = rowVar == colVar ? "border: 1px solid var(--purple-accent);" : ""
                let displayVal = rowVar == colVar ? "1.0" : (absVal > 0.01 ? String(format: "%.2f", val) : "—")
                
                html += """
                <td style="text-align: center; font-weight: 700; background-color: \(cellColor); color: \(textColor); \(cellBorder) padding: 8px 4px; font-size: 0.75rem;">
                    \(displayVal)
                </td>
                """
            }
            html += "</tr>"
        }
        html += """
                    </tbody>
                </table>
            </div>
            <div style="margin-top: 10px; font-size: 0.75rem; color: var(--text-secondary); text-align: center; display: flex; justify-content: center; gap: 15px;">
                <span><span style="display: inline-block; width: 10px; height: 10px; background-color: rgba(59, 130, 246, 0.8); border-radius: 2px;"></span> Positive correlation</span>
                <span><span style="display: inline-block; width: 10px; height: 10px; background-color: rgba(239, 68, 68, 0.8); border-radius: 2px;"></span> Negative correlation</span>
            </div>
        </div>
        """
        return html
    }

    static func compileCorrelationsSectionHTML(result: AnalysisResult) -> String {
        guard !result.correlations.isEmpty else { return "" }
        
        let hasMatrix = result.confusionMatrix != nil || result.valConfusionMatrix != nil
        let pageBreakClass = hasMatrix ? "" : "page-break"
        
        var html = "<div class='\(pageBreakClass)'>"
        html += "<div class='card' style='break-inside: avoid;'>"
        html += "<div class='card-title'>🔗 Top Feature Correlations</div>"
        html += "<div class='table-wrapper'><table>"
        html += "<thead><tr><th>Feature A</th><th>Feature B</th><th>Correlation Coefficient</th><th>Strength</th></tr></thead>"
        html += "<tbody>"
        for corr in result.correlations.prefix(10) {
            let absVal = abs(corr.value)
            let badgeClass: String
            let strengthText: String
            if absVal >= 0.7 {
                badgeClass = "badge-warning"
                strengthText = "Strong"
            } else if absVal >= 0.4 {
                badgeClass = "badge-info"
                strengthText = "Moderate"
            } else {
                badgeClass = "badge-info"
                strengthText = "Weak"
            }
            
            html += "<tr>"
            html += "<td><code>\(corr.x)</code></td>"
            html += "<td><code>\(corr.y)</code></td>"
            html += "<td style='font-weight: 600; color: \(corr.value >= 0 ? "#34d399" : "#f87171")'>\(String(format: "%.3f", corr.value))</td>"
            html += "<td><span class='badge \(badgeClass)'>\(strengthText)</span></td>"
            html += "</tr>"
        }
        html += "</tbody></table></div></div></div>"
        return html
    }

    static func compileWarningsHTML(result: AnalysisResult) -> String {
        var html = ""
        let warnings = result.dataLeakageWarnings ?? []
        let recs = result.cleaningRecommendations ?? []
        
        if !warnings.isEmpty || !recs.isEmpty {
            html += "<div class='card' style='break-inside: avoid;'>"
            html += "<div class='card-title'>⚠️ Data Quality & Leakage Warnings</div>"
            for warning in warnings {
                html += "<div class='leakage-warning'><strong>Leakage Warning:</strong> \(warning)</div>"
            }
            if !recs.isEmpty {
                html += "<div class='table-wrapper'><table>"
                html += "<thead><tr><th>Column</th><th>Issue</th><th>Recommendation</th><th>Impact</th></tr></thead>"
                html += "<tbody>"
                for rec in recs {
                    html += "<tr>"
                    html += "<td><code>\(rec.column)</code></td>"
                    html += "<td>\(rec.issue)</td>"
                    html += "<td>\(rec.recommendation)</td>"
                    html += "<td><span class='badge badge-warning'>\(rec.impact)</span></td>"
                    html += "</tr>"
                }
                html += "</tbody></table></div>"
            }
            html += "</div>"
        }
        return html
    }

    static func compileSampleTableHTML(result: AnalysisResult, includeTable: Bool) -> String {
        guard includeTable, let fp = result.fullPreview else { return "" }
        var html = "<div class='card page-break' style='break-inside: avoid;'>"
        html += "<div class='card-title'>🗃️ Dataset Preview (First 50 Rows)</div>"
        html += "<div class='table-wrapper'><table>"
        html += "<thead><tr>"
        for col in fp.columns {
            html += "<th>\(col)</th>"
        }
        html += "</tr></thead><tbody>"
        for row in fp.rows.prefix(50) {
            html += "<tr>"
            for val in row {
                html += "<td>\(val)</td>"
            }
            html += "</tr>"
        }
        html += "</tbody></table></div>"
        html += "</div>"
        return html
    }
}
