import Foundation

@MainActor
struct ReportCompiler {
    static func buildMarkdownReport(result: AnalysisResult, narrative: String?, includeStats: Bool = true, includeCharts: Bool = true, includeTable: Bool = false) -> String {
        var md = ""
        if let narrative = narrative {
            md += narrative + "\n\n---\n\n"
        }
        md += "# Analysis Report: \(result.targetColumn)\n\n"
        md += "_Generated by Aura — \(Date().formatted(date: .long, time: .shortened))_\n\n"
        md += "---\n\n"

        if includeStats {
            md += "## 📊 Dataset Overview\n\n"
            md += "| Metric | Value |\n|---|---|\n"
            md += "| Rows | \(result.rowCount) |\n"
            md += "| Columns | \(result.colCount) |\n"
            md += "| Task Type | \(result.taskType.capitalized) |\n"
            md += "| Target Column | `\(result.targetColumn)` |\n"
            md += "| Numeric Columns | \(result.numericColCount) |\n"
            md += "| Categorical Columns | \(result.categoricalColCount) |\n\n"

            md += "### 🤖 Model Performance\n\n"
            md += "| Model | \(result.metrics.scoreType) |\n|---|---|\n"
            for model in result.modelsCompared {
                md += "| \(model.name) | \(String(format: "%.4f", model.score)) |\n"
            }
            md += "\n"

            let missingCols = result.missingValues.filter { $0.value > 0 }
            if !missingCols.isEmpty {
                md += "### ⚠️ Missing Values\n\n"
                md += "| Column | Missing Count |\n|---|---|\n"
                for (col, count) in missingCols.sorted(by: { $0.value > $1.value }) {
                    md += "| `\(col)` | \(count) |\n"
                }
                md += "\n"
            }
        }

        if includeCharts && !result.charts.isEmpty {
            md += "## 📈 Charts\n\n"
            for chart in result.charts {
                md += "### \(chart.title)\n\n"
                md += "_\(chart.xLabel) → \(chart.yLabel)_\n\n"
                md += "| \(chart.xLabel) | \(chart.yLabel) |\n|---|---|\n"
                for point in chart.data.prefix(20) {
                    let x = point.xVal ?? (point.xNum.map { String(format: "%.4f", $0) } ?? "—")
                    md += "| \(x) | \(String(format: "%.6f", point.y)) |\n"
                }
                if chart.data.count > 20 {
                    md += "\n_… \(chart.data.count - 20) more points not shown_\n"
                }
                md += "\n"
            }
        }

        if includeTable, let fp = result.fullPreview {
            md += "## 🗃️ Data Sample (first 50 rows)\n\n"
            md += "| " + fp.columns.joined(separator: " | ") + " |\n"
            md += "|" + fp.columns.map { _ in "---" }.joined(separator: "|") + "|\n"
            for row in fp.rows.prefix(50) {
                md += "| " + row.joined(separator: " | ") + " |\n"
            }
            md += "\n"
        }

        if !result.correlations.isEmpty {
            md += "## 🔗 Top Correlations\n\n"
            md += "| Feature A | Feature B | Correlation |\n|---|---|---|\n"
            for corr in result.correlations.prefix(10) {
                md += "| `\(corr.x)` | `\(corr.y)` | \(String(format: "%.3f", corr.value)) |\n"
            }
            md += "\n"
        }

        if result.confusionMatrix != nil || result.valConfusionMatrix != nil {
            md += "## 🧩 Confusion Matrices\n\n"
            if let cm = result.confusionMatrix {
                md += "### Confusion Matrix (Test Set)\n\n"
                md += "| Actual \\ Predicted | " + cm.labels.joined(separator: " | ") + " |\n"
                md += "|---| " + cm.labels.map { _ in "---" }.joined(separator: "|") + " |\n"
                for i in 0..<cm.labels.count {
                    var rowStr = "| **\(cm.labels[i])**"
                    for j in 0..<cm.labels.count {
                        let val = i < cm.values.count && j < cm.values[i].count ? cm.values[i][j] : 0
                        rowStr += " | \(val)"
                    }
                    md += rowStr + " |\n"
                }
                md += "\n"
            }
            if let cm = result.valConfusionMatrix {
                md += "### Confusion Matrix (Validation Set)\n\n"
                md += "| Actual \\ Predicted | " + cm.labels.joined(separator: " | ") + " |\n"
                md += "|---| " + cm.labels.map { _ in "---" }.joined(separator: "|") + " |\n"
                for i in 0..<cm.labels.count {
                    var rowStr = "| **\(cm.labels[i])**"
                    for j in 0..<cm.labels.count {
                        let val = i < cm.values.count && j < cm.values[i].count ? cm.values[i][j] : 0
                        rowStr += " | \(val)"
                    }
                    md += rowStr + " |\n"
                }
                md += "\n"
            }
        }

        if !result.correlations.isEmpty {
            md += "## 📊 Feature Correlation Matrix\n\n"
            var seen = Set<String>()
            var uniqueVars: [String] = []
            for pair in result.correlations {
                if !seen.contains(pair.x) { seen.insert(pair.x); uniqueVars.append(pair.x) }
                if !seen.contains(pair.y) { seen.insert(pair.y); uniqueVars.append(pair.y) }
            }
            let varsToDraw = Array(uniqueVars.prefix(10))
            if !varsToDraw.isEmpty {
                var correlationLookup: [String: Double] = [:]
                for pair in result.correlations {
                    correlationLookup["\(pair.x)|\(pair.y)"] = pair.value
                    correlationLookup["\(pair.y)|\(pair.x)"] = pair.value
                }
                
                md += "| Feature | " + varsToDraw.joined(separator: " | ") + " |\n"
                md += "|---| " + varsToDraw.map { _ in "---" }.joined(separator: "|") + " |\n"
                for rowVar in varsToDraw {
                    var rowStr = "| `\(rowVar)`"
                    for colVar in varsToDraw {
                        if rowVar == colVar {
                            rowStr += " | 1.00"
                        } else {
                            let key = "\(rowVar)|\(colVar)"
                            if let val = correlationLookup[key] {
                                rowStr += String(format: " | %.2f", val)
                            } else {
                                rowStr += " | —"
                            }
                        }
                    }
                    md += rowStr + " |\n"
                }
                md += "\n"
            }
        }

        return md
    }

    static func buildHTMLReport(result: AnalysisResult, narrative: String?, includeTable: Bool = false, isForPDF: Bool = false) -> String {
        let targetColEscaped = result.targetColumn.replacingOccurrences(of: "\"", with: "\\\"")
        
        let modelsComparedData = try? JSONEncoder().encode(result.modelsCompared)
        let modelsComparedJSON = modelsComparedData.flatMap { String(data: $0, encoding: .utf8) } ?? "[]"
        
        let encoder = JSONEncoder()
        let chartsData = try? encoder.encode(result.charts)
        let chartsJSON = chartsData.flatMap { String(data: $0, encoding: .utf8) } ?? "[]"

        let narrativeMarkdownEscaped = (narrative ?? "").replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "`", with: "\\`")
            .replacingOccurrences(of: "$", with: "\\$")

        let htmlContent = """
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Aura Analysis Report - \(targetColEscaped)</title>
            <style>
                :root {
                    --bg-color: \(isForPDF ? "#ffffff" : "#0b0c10");
                    --card-bg: \(isForPDF ? "#ffffff" : "#1a1c23");
                    --border-color: \(isForPDF ? "#e2e8f0" : "rgba(255, 255, 255, 0.06)");
                    --text-color: \(isForPDF ? "#0f172a" : "#e2e8f0");
                    --text-secondary: \(isForPDF ? "#475569" : "#94a3b8");
                    --purple-accent: #a78bfa;
                    --indigo-accent: #6366f1;
                }
                body {
                    background-color: var(--bg-color);
                    color: var(--text-color);
                    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
                    margin: 0;
                    padding: 40px 20px;
                    line-height: 1.5;
                }
                .container {
                    max-width: 800px;
                    margin: 0 auto;
                }
                .header {
                    margin-bottom: 40px;
                    padding-bottom: 24px;
                    border-bottom: 1px solid var(--border-color);
                    display: flex;
                    justify-content: space-between;
                    align-items: center;
                }
                .header h1 {
                    font-size: 2.2rem;
                    margin: 0 0 8px 0;
                    background: linear-gradient(135deg, var(--purple-accent), var(--indigo-accent));
                    -webkit-background-clip: text;
                    -webkit-text-fill-color: transparent;
                    font-weight: 800;
                }
                .header p {
                    color: var(--text-secondary);
                    margin: 0;
                    font-size: 0.95rem;
                }
                .logo {
                    font-size: 1.8rem;
                    font-weight: 900;
                    background: linear-gradient(135deg, #f43f5e, #a855f7);
                    -webkit-background-clip: text;
                    -webkit-text-fill-color: transparent;
                }
                .grid-4 {
                    display: grid;
                    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
                    gap: 16px;
                    margin-bottom: 30px;
                }
                .stat-card {
                    background-color: var(--card-bg);
                    border: 1px solid var(--border-color);
                    border-radius: 12px;
                    padding: 18px;
                    text-align: center;
                }
                .stat-value {
                    font-size: 1.8rem;
                    font-weight: 700;
                    margin-bottom: 4px;
                    color: var(--text-color);
                }
                .stat-label {
                    font-size: 0.8rem;
                    color: var(--text-secondary);
                    text-transform: uppercase;
                    letter-spacing: 0.5px;
                }
                .card {
                    background-color: var(--card-bg);
                    border: 1px solid var(--border-color);
                    border-radius: 16px;
                    padding: 24px;
                    margin-bottom: 24px;
                    box-shadow: \(isForPDF ? "none" : "0 4px 20px rgba(0, 0, 0, 0.2)");
                }
                .card-title {
                    font-size: 1.15rem;
                    font-weight: 600;
                    margin-top: 0;
                    margin-bottom: 20px;
                    color: var(--purple-accent);
                    display: flex;
                    align-items: center;
                    gap: 8px;
                    border-bottom: 1px solid rgba(255, 255, 255, 0.04);
                    padding-bottom: 12px;
                }
                .chart-container {
                    width: 100%;
                    height: 350px;
                    margin-top: 15px;
                }
                .grid-2 {
                    display: grid;
                    grid-template-columns: repeat(auto-fit, minmax(360px, 1fr));
                    gap: 20px;
                    margin-bottom: 24px;
                }
                .table-wrapper {
                    overflow-x: auto;
                }
                table {
                    width: 100%;
                    border-collapse: collapse;
                    margin-top: 10px;
                }
                th, td {
                    text-align: left;
                    padding: 10px 14px;
                    border-bottom: 1px solid var(--border-color);
                    font-size: 0.9rem;
                    color: var(--text-color);
                }
                th {
                    background-color: rgba(255, 255, 255, 0.02);
                    color: var(--purple-accent);
                    font-weight: 600;
                }
                tr:hover {
                    background-color: rgba(255, 255, 255, 0.01);
                }
                .badge {
                    display: inline-block;
                    padding: 3px 6px;
                    border-radius: 4px;
                    font-size: 0.75rem;
                    font-weight: 600;
                }
                .badge-warning {
                    background-color: rgba(245, 158, 11, 0.12);
                    color: #fbbf24;
                    border: 1px solid rgba(245, 158, 11, 0.25);
                }
                .badge-info {
                    background-color: rgba(59, 130, 246, 0.12);
                    color: #60a5fa;
                    border: 1px solid rgba(59, 130, 246, 0.25);
                }
                .narrative {
                    line-height: 1.6;
                    color: var(--text-color);
                }
                .narrative h2, .narrative h3 {
                    color: var(--purple-accent);
                    margin-top: 24px;
                }
                .narrative p {
                    margin-bottom: 16px;
                }
                .narrative ul {
                    padding-left: 20px;
                    margin-bottom: 16px;
                }
                .narrative li {
                    margin-bottom: 6px;
                }
                .leakage-warning {
                    background-color: rgba(239, 68, 68, 0.08);
                    border: 1px solid rgba(239, 68, 68, 0.2);
                    color: #f87171;
                    padding: 12px 16px;
                    border-radius: 8px;
                    margin-bottom: 16px;
                    font-size: 0.9rem;
                }
                @media print {
                    @page {
                        size: A4 portrait;
                        margin: 20mm 15mm 20mm 15mm;
                    }
                    :root {
                        --bg-color: #ffffff;
                        --card-bg: #ffffff;
                        --border-color: #e2e8f0;
                        --text-color: #0f172a;
                        --text-secondary: #475569;
                    }
                    body {
                        background-color: #ffffff !important;
                        color: #0f172a !important;
                        padding: 0 !important;
                        margin: 0 !important;
                    }
                    .container {
                        max-width: 100% !important;
                        width: 100% !important;
                        padding: 0 !important;
                        margin: 0 !important;
                    }
                    .page-break {
                        page-break-before: always !important;
                        break-before: page !important;
                    }
                    .card, .stat-card {
                        background-color: #ffffff !important;
                        border: 1px solid #e2e8f0 !important;
                        box-shadow: none !important;
                        page-break-inside: avoid !important;
                        break-inside: avoid !important;
                        margin-bottom: 20px !important;
                    }
                    .grid-2 {
                        display: block !important;
                    }
                    .grid-2 > .card {
                        width: 100% !important;
                        margin-bottom: 20px !important;
                    }
                    .stat-value {
                        color: #0f172a !important;
                    }
                    .header h1 {
                        -webkit-text-fill-color: initial !important;
                        color: #1e1b4b !important;
                    }
                    th {
                        background-color: #f8fafc !important;
                        color: #1e293b !important;
                    }
                    td, th {
                        border-bottom: 1px solid #e2e8f0 !important;
                        color: #1e293b !important;
                    }
                    code {
                        background-color: #f1f5f9 !important;
                        color: #0f172a !important;
                        border: 1px solid #e2e8f0 !important;
                    }
                    .badge-info {
                        background-color: #eff6ff !important;
                        color: #1d4ed8 !important;
                        border: 1px solid #bfdbfe !important;
                    }
                    .badge-warning {
                        background-color: #fffbeb !important;
                        color: #b45309 !important;
                        border: 1px solid #fde68a !important;
                    }
                    h1, h2, h3, h4, h5, h6 {
                        page-break-after: avoid !important;
                        break-after: avoid !important;
                    }
                    tr {
                        page-break-inside: avoid !important;
                        break-inside: avoid !important;
                    }
                }
            </style>
            <script src="https://cdn.jsdelivr.net/npm/echarts@5.4.3/dist/echarts.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <div>
                        <h1>Aura Analysis Report</h1>
                        <p>Target: <code>\(result.targetColumn)</code> &bull; Generated on \(Date().formatted(date: .long, time: .shortened))</p>
                    </div>
                    <div class="logo">Aura</div>
                </div>

                <div class="grid-4">
                    <div class="stat-card">
                        <div class="stat-value">\(result.rowCount)</div>
                        <div class="stat-label">Rows</div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-value">\(result.colCount)</div>
                        <div class="stat-label">Columns</div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-value">\(result.taskType.capitalized)</div>
                        <div class="stat-label">Task Type</div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-value">\(String(format: "%.4f", result.metrics.score))</div>
                        <div class="stat-label">\(result.metrics.scoreType)</div>
                    </div>
                </div>

                <!-- AI Executive Summary -->
                <div id="narrative-card" class="card" style="display: none;">
                    <div class="card-title">✨ AI Executive Summary</div>
                    <div id="narrative-content" class="narrative"></div>
                </div>

                <!-- Data Quality Warnings -->
                \(compileWarningsHTML(result: result))

                <!-- Model Performance Card -->
                <div class="card page-break">
                    <div class="card-title">🤖 Model Performance Leaderboard</div>
                    <div id="model-chart" class="chart-container" style="height: 300px;"></div>
                </div>

                <!-- Analysis & Diagnostic Charts -->
                <div id="charts-section" class="page-break" style="margin-top: 30px;">
                    <h2 style="color: var(--purple-accent); border-bottom: 1px solid var(--border-color); padding-bottom: 8px; margin-bottom: 20px;">📊 Analysis & Diagnostic Visualizations</h2>
                    <div id="charts-grid" class="grid-2">
                        <!-- Dynamic charts will be appended here -->
                    </div>
                </div>

                <!-- Confusion Matrices -->
                \(compileConfusionMatricesHTML(result: result))

                <!-- Feature Correlation Matrix -->
                \(compileCorrelationMatrixHTML(result: result))

                <!-- Top Correlations -->
                \(compileCorrelationsSectionHTML(result: result))

                <!-- Dataset Sample -->
                \(compileSampleTableHTML(result: result, includeTable: includeTable))
            </div>

            <script>
                // Injected data
                var narrativeMarkdown = `\(narrativeMarkdownEscaped)`;
                var modelData = \(modelsComparedJSON);
                var chartsList = \(chartsJSON);
                var isPDF = \(isForPDF ? "true" : "false");
                
                // Color configuration matching active theme context
                var textColor = isPDF ? '#334155' : '#e2e8f0';
                var axisLineColor = isPDF ? '#cbd5e1' : 'rgba(255,255,255,0.1)';
                var splitLineColor = isPDF ? '#f1f5f9' : 'rgba(255,255,255,0.04)';
                
                // Render narrative
                if (narrativeMarkdown.trim().length > 0) {
                    document.getElementById('narrative-card').style.display = 'block';
                    document.getElementById('narrative-content').innerHTML = marked.parse(narrativeMarkdown);
                }

                // Render Model Leaderboard
                if (modelData && modelData.length > 0) {
                    var chart = echarts.init(document.getElementById('model-chart'));
                    chart.setOption({
                        animation: false,
                        tooltip: { trigger: 'axis', axisPointer: { type: 'shadow' } },
                        grid: { left: '3%', right: '4%', bottom: '15%', top: '5%', containLabel: true },
                        xAxis: { 
                            type: 'category', 
                            data: modelData.map(m => m.name), 
                            axisLabel: { interval: 0, rotate: modelData.length > 4 ? 15 : 0, color: textColor },
                            axisLine: { lineStyle: { color: axisLineColor } }
                        },
                        yAxis: { 
                            type: 'value', 
                            name: 'Score',
                            axisLabel: { color: textColor },
                            axisLine: { lineStyle: { color: axisLineColor } },
                            splitLine: { lineStyle: { color: splitLineColor } }
                        },
                        series: [{
                            data: modelData.map(m => m.score),
                            type: 'bar',
                            itemStyle: { color: '#6366f1', borderRadius: [4, 4, 0, 0] }
                        }]
                    });
                }

                // ECharts Boxplot config builder
                function getBoxplotOption(cfg) {
                    var stats = cfg.box_stats;
                    if (!stats) return null;
                    var boxData = [[stats.min, stats.q1, stats.median, stats.q3, stats.max]];
                    var outlierData = (stats.outliers || []).map(val => [0, val]);
                    
                    var series = [{
                        name: 'Boxplot',
                        type: 'boxplot',
                        data: boxData,
                        itemStyle: {
                            color: isPDF ? 'rgba(99, 102, 241, 0.15)' : 'rgba(167, 139, 250, 0.25)',
                            borderColor: '#a78bfa',
                            borderWidth: 2
                        }
                    }];
                    if (outlierData.length > 0) {
                        series.push({
                            name: 'Outlier',
                            type: 'scatter',
                            data: outlierData,
                            itemStyle: { color: '#f43f5e' },
                            symbolSize: 8
                        });
                    }
                    
                    return {
                        animation: false,
                        tooltip: { trigger: 'item' },
                        grid: { left: '8%', right: '8%', bottom: '10%', top: '10%', containLabel: true },
                        xAxis: {
                            type: 'category',
                            data: [cfg.y_label || 'Stats'],
                            axisLabel: { color: textColor },
                            axisLine: { lineStyle: { color: axisLineColor } },
                            splitLine: { show: false }
                        },
                        yAxis: {
                            type: 'value',
                            axisLabel: { color: textColor },
                            axisLine: { lineStyle: { color: axisLineColor } },
                            splitLine: { lineStyle: { color: splitLineColor } }
                        },
                        series: series
                    };
                }

                // ECharts SHAP Beeswarm config builder
                function getBeeswarmOption(cfg) {
                    var features = [...new Set(cfg.data.map(pt => pt.x_val))];
                    var dataPoints = [];
                    
                    features.forEach((feat, fIdx) => {
                        var pts = cfg.data.filter(pt => pt.x_val === feat).sort((a,b) => a.x_num - b.x_num);
                        var placed = [];
                        var cellWidth = 0.015;
                        if (pts.length > 0) {
                            var xMin = Math.min(...pts.map(p => p.x_num));
                            var xMax = Math.max(...pts.map(p => p.x_num));
                            var xRange = xMax - xMin;
                            if (xRange > 0) cellWidth = xRange * 0.02;
                        }
                        var diameter = 0.08;
                        
                        pts.forEach(pt => {
                            var neighbors = placed.filter(p => Math.abs(p.x - pt.x_num) < cellWidth);
                            var offset = 0.0;
                            var found = false;
                            var step = 0;
                            
                            while (!found) {
                                var candidate = 0.0;
                                if (step === 0) {
                                    candidate = 0.0;
                                } else if (step % 2 === 1) {
                                    candidate = Math.ceil(step / 2) * diameter;
                                } else {
                                    candidate = -(step / 2) * diameter;
                                }
                                
                                var collides = neighbors.some(n => Math.abs(n.offset - candidate) < (diameter * 0.85));
                                if (!collides || Math.abs(candidate) >= 0.4) {
                                    offset = Math.min(Math.max(candidate, -0.4), 0.4);
                                    found = true;
                                } else {
                                    step++;
                                }
                            }
                            
                            var yPos = fIdx + offset;
                            placed.push({ x: pt.x_num, offset: offset });
                            dataPoints.push([pt.x_num, yPos, pt.y, pt.x_val]);
                        });
                    });

                    return {
                        animation: false,
                        tooltip: {
                            trigger: 'item',
                            formatter: function (params) {
                                return 'Feature: ' + params.value[3] + '<br/>SHAP Value: ' + params.value[0].toFixed(4) + '<br/>Feature Value: ' + params.value[2].toFixed(4);
                            }
                        },
                        grid: { left: '15%', right: '5%', bottom: '15%', top: '5%', containLabel: true },
                        xAxis: { 
                            type: 'value', 
                            name: 'SHAP Value (Impact on Prediction)',
                            axisLabel: { color: textColor },
                            axisLine: { lineStyle: { color: axisLineColor } },
                            splitLine: { lineStyle: { color: splitLineColor } }
                        },
                        yAxis: {
                            type: 'value',
                            min: -0.5,
                            max: features.length - 0.5,
                            interval: 1,
                            axisLabel: {
                                color: textColor,
                                formatter: function (value) {
                                    return features[Math.round(value)] || '';
                                }
                            },
                            axisLine: { lineStyle: { color: axisLineColor } },
                            splitLine: { show: false }
                        },
                        visualMap: {
                            min: 0,
                            max: 1,
                            dimension: 2,
                            calculable: true,
                            orient: 'horizontal',
                            left: 'center',
                            bottom: '0%',
                            text: ['High', 'Low'],
                            textStyle: { color: textColor },
                            inRange: {
                                color: ['#2563eb', '#a855f7', '#ec4899', '#ef4444']
                            }
                        },
                        series: [{
                            type: 'scatter',
                            symbolSize: 6,
                            data: dataPoints
                        }]
                    };
                }

                // ECharts PDP & ICE curves builder
                function getPdpOption(cfg) {
                    var seriesMap = {};
                    cfg.data.forEach(pt => {
                        var s = pt.series || 'PDP';
                        if (!seriesMap[s]) seriesMap[s] = [];
                        seriesMap[s].push([pt.x_num, pt.y]);
                    });

                    var seriesConfig = [];
                    Object.keys(seriesMap).forEach(s => {
                        if (s !== 'PDP') {
                            seriesConfig.push({
                                name: s,
                                type: 'line',
                                data: seriesMap[s].sort((a,b) => a[0] - b[0]),
                                lineStyle: { width: 0.8, color: '#94a3b8', opacity: 0.15 },
                                showSymbol: false,
                                animation: false
                            });
                        }
                    });
                    if (seriesMap['PDP']) {
                        seriesConfig.push({
                            name: 'PDP',
                            type: 'line',
                            data: seriesMap['PDP'].sort((a,b) => a[0] - b[0]),
                            lineStyle: { width: 3, color: '#a78bfa' },
                            showSymbol: false,
                            animation: false
                        });
                    }

                    return {
                        animation: false,
                        tooltip: { trigger: 'axis' },
                        grid: { left: '3%', right: '4%', bottom: '5%', top: '5%', containLabel: true },
                        xAxis: { 
                            type: 'value', 
                            name: cfg.x_label, 
                            nameLocation: 'middle', 
                            nameGap: 20,
                            axisLabel: { color: textColor },
                            axisLine: { lineStyle: { color: axisLineColor } },
                            splitLine: { lineStyle: { color: splitLineColor } }
                        },
                        yAxis: { 
                            type: 'value', 
                            name: cfg.y_label,
                            axisLabel: { color: textColor },
                            axisLine: { lineStyle: { color: axisLineColor } },
                            splitLine: { lineStyle: { color: splitLineColor } }
                        },
                        series: seriesConfig
                    };
                }

                // Standard ECharts Line / Bar / Scatter builder
                function getStandardChartOption(cfg) {
                    var seriesMap = {};
                    cfg.data.forEach(pt => {
                        var sName = pt.series || 'Value';
                        if (!seriesMap[sName]) seriesMap[sName] = [];
                        var xVal = pt.x_val !== null ? pt.x_val : pt.x_num;
                        seriesMap[sName].push([xVal, pt.y]);
                    });
                    
                    var seriesList = [];
                    var categories = [];
                    var isCategoricalX = cfg.data.some(pt => pt.x_val !== null);
                    
                    if (isCategoricalX) {
                        var catSet = new Set();
                        cfg.data.forEach(pt => {
                            if (pt.x_val !== null) catSet.add(pt.x_val);
                        });
                        categories = Array.from(catSet);
                    }
                    
                    Object.keys(seriesMap).forEach(sName => {
                        var sData = seriesMap[sName];
                        if (isCategoricalX) {
                            var mappedData = categories.map(cat => {
                                var match = sData.find(d => d[0] === cat);
                                return match ? match[1] : 0;
                            });
                            seriesList.push({
                                name: sName,
                                type: cfg.type,
                                data: mappedData,
                                itemStyle: { borderRadius: cfg.type === 'bar' ? [4, 4, 0, 0] : 0 }
                            });
                        } else {
                            seriesList.push({
                                name: sName,
                                type: cfg.type,
                                data: sData.sort((a, b) => a[0] - b[0]),
                                showSymbol: cfg.type !== 'line',
                                lineStyle: { width: 2 }
                            });
                        }
                    });
                    
                    return {
                        animation: false,
                        tooltip: { trigger: 'axis' },
                        legend: { 
                            show: Object.keys(seriesMap).length > 1,
                            textStyle: { color: textColor },
                            bottom: 0
                        },
                        grid: { left: '3%', right: '4%', bottom: Object.keys(seriesMap).length > 1 ? '12%' : '8%', top: '10%', containLabel: true },
                        xAxis: {
                            type: isCategoricalX ? 'category' : 'value',
                            data: isCategoricalX ? categories : undefined,
                            name: cfg.x_label,
                            nameLocation: 'middle',
                            nameGap: 25,
                            axisLabel: { color: textColor, rotate: isCategoricalX && categories.length > 8 ? 20 : 0 },
                            axisLine: { lineStyle: { color: axisLineColor } },
                            splitLine: { lineStyle: { color: splitLineColor } }
                        },
                        yAxis: {
                            type: 'value',
                            name: cfg.y_label,
                            axisLabel: { color: textColor },
                            axisLine: { lineStyle: { color: axisLineColor } },
                            splitLine: { lineStyle: { color: splitLineColor } }
                        },
                        series: seriesList,
                        color: ['#6366f1', '#a78bfa', '#ec4899', '#f43f5e', '#3b82f6', '#10b981', '#f59e0b']
                    };
                }

                // HTML WordCloud renderer
                function renderWordCloud(cfg) {
                    var maxWeight = Math.max(...cfg.data.map(pt => pt.y)) || 1.0;
                    var minWeight = Math.min(...cfg.data.map(pt => pt.y)) || 0.0;
                    var weightRange = Math.max(0.0001, maxWeight - minWeight);
                    var colors = ['#3b82f6', '#a78bfa', '#ec4899', '#6366f1', '#14b8a6', '#f59e0b', '#06b6d4', '#10b981'];
                    
                    var html = '<div style="display: flex; flex-wrap: wrap; justify-content: center; align-items: center; gap: 8px; padding: 20px; background: rgba(255,255,255,0.02); border-radius: 8px; min-height: 200px;">';
                    cfg.data.forEach((pt, index) => {
                        if (pt.x_val) {
                            var norm = (pt.y - minWeight) / weightRange;
                            var size = 12 + norm * 20; // 12px to 32px
                            var col = colors[index % colors.length];
                            html += `<span style="font-size: ${size}px; color: ${col}; font-weight: 600; padding: 4px 8px; margin: 4px; background: ${col}10; border-radius: 4px; display: inline-block;">${pt.x_val}</span>`;
                        }
                    });
                    html += '</div>';
                    return html;
                }

                // HTML ImageGrid renderer
                function renderImageGrid(cfg) {
                    var html = '<div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(120px, 1fr)); gap: 16px; padding: 10px;">';
                    (cfg.images || []).forEach(img => {
                        html += `
                        <div style="text-align: center; padding: 8px; background: rgba(255,255,255,0.03); border-radius: 8px; border: 1px solid rgba(255,255,255,0.05); break-inside: avoid;">
                            <img src="data:image/png;base64,${img.base64}" style="width: 100px; height: 100px; object-fit: contain; border-radius: 4px;" />
                            <div style="font-size: 0.75rem; margin-top: 6px; font-weight: 500; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; color: ${textColor};">${img.label}</div>
                        </div>
                        `;
                    });
                    html += '</div>';
                    return html;
                }

                // Initialize all analysis charts
                if (chartsList && chartsList.length > 0) {
                    var container = document.getElementById('charts-grid');
                    chartsList.forEach(function(chart, index) {
                        var card = document.createElement('div');
                        card.className = 'card';
                        card.style.breakInside = 'avoid';
                        
                        var title = document.createElement('div');
                        title.className = 'card-title';
                        title.innerText = chart.title;
                        card.appendChild(title);
                        
                        if (chart.type === 'wordcloud') {
                            var cloudDiv = document.createElement('div');
                            cloudDiv.innerHTML = renderWordCloud(chart);
                            card.appendChild(cloudDiv);
                            container.appendChild(card);
                        } else if (chart.type === 'image_grid') {
                            var gridDiv = document.createElement('div');
                            gridDiv.innerHTML = renderImageGrid(chart);
                            card.appendChild(gridDiv);
                            container.appendChild(card);
                        } else {
                            var chartDiv = document.createElement('div');
                            var chartId = 'analysis-chart-' + index;
                            chartDiv.id = chartId;
                            chartDiv.className = 'chart-container';
                            if (chart.type === 'shap_beeswarm') {
                                chartDiv.style.height = '480px';
                            } else if (chart.type === 'boxplot' || chart.type === 'pdp_ice') {
                                chartDiv.style.height = '280px';
                            }
                            card.appendChild(chartDiv);
                            container.appendChild(card);
                            
                            var myChart = echarts.init(chartDiv);
                            var option = null;
                            if (chart.type === 'boxplot') {
                                option = getBoxplotOption(chart);
                            } else if (chart.type === 'shap_beeswarm') {
                                option = getBeeswarmOption(chart);
                            } else if (chart.type === 'pdp_ice') {
                                option = getPdpOption(chart);
                            } else {
                                option = getStandardChartOption(chart);
                            }
                            
                            if (option) {
                                myChart.setOption(option);
                            }
                        }
                    });
                }
            </script>
        </body>
        </html>
        """
        return htmlContent
    }

    static func compileConfusionMatricesHTML(result: AnalysisResult) -> String {
        var html = ""
        let hasTest = result.confusionMatrix != nil
        let hasVal = result.valConfusionMatrix != nil
        
        if hasTest || hasVal {
            html += "<div class='grid-2 page-break'>"
            if hasTest {
                html += compileConfusionMatrixHTML(title: "Confusion Matrix (Test Set)", matrix: result.confusionMatrix)
            }
            if hasVal {
                html += compileConfusionMatrixHTML(title: "Confusion Matrix (Validation Set)", matrix: result.valConfusionMatrix)
            }
            html += "</div>"
        }
        return html
    }

    static func compileConfusionMatrixHTML(title: String, matrix: ConfusionMatrixData?) -> String {
        guard let matrix = matrix else { return "" }
        let labels = matrix.labels
        let values = matrix.values
        let maxVal = values.flatMap { $0 }.max() ?? 1
        
        var html = """
        <div class="card" style="break-inside: avoid;">
            <div class="card-title">🧩 \(title)</div>
            <div class="table-wrapper" style="margin-top: 15px;">
                <table style="border: none; margin: 0 auto; max-width: 450px; text-align: center;">
                    <thead>
                        <tr>
                            <th style="border: none; background: transparent;"></th>
                            <th colspan="\(labels.count)" style="text-align: center; border-bottom: 2px solid var(--indigo-accent); color: var(--purple-accent); font-weight: 700;">Predicted</th>
                        </tr>
                        <tr>
                            <th style="text-align: right; border-right: 2px solid var(--indigo-accent); color: var(--purple-accent); font-weight: 700; padding-right: 15px;">Actual</th>
        """
        for label in labels {
            html += "<th style='text-align: center; font-weight: 600;'>\(label)</th>"
        }
        html += """
                        </tr>
                    </thead>
                    <tbody>
        """
        for i in 0..<labels.count {
            html += "<tr>"
            html += "<td style='text-align: right; font-weight: 600; border-right: 2px solid var(--indigo-accent); padding-right: 15px; color: var(--text-secondary);'>\(labels[i])</td>"
            for j in 0..<labels.count {
                let val = (i < values.count && j < values[i].count) ? values[i][j] : 0
                let ratio = Double(val) / Double(maxVal)
                let bgOpacity = 0.08 + ratio * 0.45
                let textColor = ratio > 0.6 ? "#fff" : "var(--text-color)"
                let cellBorder = i == j ? "border: 2px solid var(--purple-accent);" : ""
                
                html += """
                <td style="text-align: center; font-weight: 700; background-color: rgba(99, 102, 241, \(bgOpacity)); color: \(textColor); \(cellBorder) padding: 12px; border-radius: 6px; font-size: 1.05rem;">
                    \(val)
                </td>
                """
            }
            html += "</tr>"
        }
        html += """
                    </tbody>
                </table>
            </div>
        </div>
        """
        return html
    }
    
    static func compileCorrelationMatrixHTML(result: AnalysisResult) -> String {
        guard !result.correlations.isEmpty else { return "" }
        
        // Extract unique variables in order
        var seen = Set<String>()
        var uniqueVars: [String] = []
        for pair in result.correlations {
            if !seen.contains(pair.x) {
                seen.insert(pair.x)
                uniqueVars.append(pair.x)
            }
            if !seen.contains(pair.y) {
                seen.insert(pair.y)
                uniqueVars.append(pair.y)
            }
        }
        
        // Cap to top 15 variables to prevent table overflow on A4 pages
        let varsToDraw = Array(uniqueVars.prefix(15))
        guard !varsToDraw.isEmpty else { return "" }
        
        // Build lookup
        var correlationLookup: [String: Double] = [:]
        for pair in result.correlations {
            let key1 = "\(pair.x)|\(pair.y)"
            let key2 = "\(pair.y)|\(pair.x)"
            correlationLookup[key1] = pair.value
            correlationLookup[key2] = pair.value
        }
        
        var html = """
        <div class="card page-break" style="break-inside: avoid;">
            <div class="card-title">📊 Feature Correlation Matrix</div>
            <div class="table-wrapper" style="margin-top: 15px; overflow-x: auto;">
                <table style="border: none; table-layout: fixed; width: 100%; border-collapse: collapse; text-align: center; font-size: 0.75rem;">
                    <thead>
                        <tr>
                            <th style="border: none; background: transparent; width: 120px;"></th>
        """
        for v in varsToDraw {
            html += "<th style='text-align: center; font-weight: 600; padding: 4px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;'>\(v)</th>"
        }
        html += """
                        </tr>
                    </thead>
                    <tbody>
        """
        for rowVar in varsToDraw {
            html += "<tr>"
            html += "<td style='text-align: right; font-weight: 600; padding: 6px 10px; border-right: 2px solid var(--indigo-accent); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; color: var(--text-secondary); width: 120px;'>\(rowVar)</td>"
            for colVar in varsToDraw {
                let val: Double
                if rowVar == colVar {
                    val = 1.0
                } else {
                    let key = "\(rowVar)|\(colVar)"
                    val = correlationLookup[key] ?? 0.0
                }
                
                let absVal = abs(val)
                let cellColor: String
                let textColor: String
                if val == 1.0 {
                    cellColor = "rgba(99, 102, 241, 0.85)"
                    textColor = "#fff"
                } else if absVal < 0.01 {
                    cellColor = "rgba(255, 255, 255, 0.02)"
                    textColor = "rgba(255, 255, 255, 0.3)"
                } else if val > 0 {
                    cellColor = "rgba(59, 130, 246, \(0.1 + absVal * 0.75))"
                    textColor = absVal > 0.5 ? "#fff" : "var(--text-color)"
                } else {
                    cellColor = "rgba(239, 68, 68, \(0.1 + absVal * 0.75))"
                    textColor = absVal > 0.5 ? "#fff" : "var(--text-color)"
                }
                
                let cellBorder = rowVar == colVar ? "border: 1px solid var(--purple-accent);" : ""
                let displayVal = rowVar == colVar ? "1.0" : (absVal > 0.01 ? String(format: "%.2f", val) : "—")
                
                html += """
                <td style="text-align: center; font-weight: 700; background-color: \(cellColor); color: \(textColor); \(cellBorder) padding: 8px 4px; font-size: 0.75rem;">
                    \(displayVal)
                </td>
                """
            }
            html += "</tr>"
        }
        html += """
                    </tbody>
                </table>
            </div>
            <div style="margin-top: 10px; font-size: 0.75rem; color: var(--text-secondary); text-align: center; display: flex; justify-content: center; gap: 15px;">
                <span><span style="display: inline-block; width: 10px; height: 10px; background-color: rgba(59, 130, 246, 0.8); border-radius: 2px;"></span> Positive correlation</span>
                <span><span style="display: inline-block; width: 10px; height: 10px; background-color: rgba(239, 68, 68, 0.8); border-radius: 2px;"></span> Negative correlation</span>
            </div>
        </div>
        """
        return html
    }

    static func compileCorrelationsSectionHTML(result: AnalysisResult) -> String {
        guard !result.correlations.isEmpty else { return "" }
        
        let hasMatrix = result.confusionMatrix != nil || result.valConfusionMatrix != nil
        let pageBreakClass = hasMatrix ? "" : "page-break"
        
        var html = "<div class='\(pageBreakClass)'>"
        html += "<div class='card' style='break-inside: avoid;'>"
        html += "<div class='card-title'>🔗 Top Feature Correlations</div>"
        html += "<div class='table-wrapper'><table>"
        html += "<thead><tr><th>Feature A</th><th>Feature B</th><th>Correlation Coefficient</th><th>Strength</th></tr></thead>"
        html += "<tbody>"
        for corr in result.correlations.prefix(10) {
            let absVal = abs(corr.value)
            let badgeClass: String
            let strengthText: String
            if absVal >= 0.7 {
                badgeClass = "badge-warning"
                strengthText = "Strong"
            } else if absVal >= 0.4 {
                badgeClass = "badge-info"
                strengthText = "Moderate"
            } else {
                badgeClass = "badge-info"
                strengthText = "Weak"
            }
            
            html += "<tr>"
            html += "<td><code>\(corr.x)</code></td>"
            html += "<td><code>\(corr.y)</code></td>"
            html += "<td style='font-weight: 600; color: \(corr.value >= 0 ? "#34d399" : "#f87171")'>\(String(format: "%.3f", corr.value))</td>"
            html += "<td><span class='badge \(badgeClass)'>\(strengthText)</span></td>"
            html += "</tr>"
        }
        html += "</tbody></table></div></div></div>"
        return html
    }

    static func compileWarningsHTML(result: AnalysisResult) -> String {
        var html = ""
        let warnings = result.dataLeakageWarnings ?? []
        let recs = result.cleaningRecommendations ?? []
        
        if !warnings.isEmpty || !recs.isEmpty {
            html += "<div class='card' style='break-inside: avoid;'>"
            html += "<div class='card-title'>⚠️ Data Quality & Leakage Warnings</div>"
            for warning in warnings {
                html += "<div class='leakage-warning'><strong>Leakage Warning:</strong> \(warning)</div>"
            }
            if !recs.isEmpty {
                html += "<div class='table-wrapper'><table>"
                html += "<thead><tr><th>Column</th><th>Issue</th><th>Recommendation</th><th>Impact</th></tr></thead>"
                html += "<tbody>"
                for rec in recs {
                    html += "<tr>"
                    html += "<td><code>\(rec.column)</code></td>"
                    html += "<td>\(rec.issue)</td>"
                    html += "<td>\(rec.recommendation)</td>"
                    html += "<td><span class='badge badge-warning'>\(rec.impact)</span></td>"
                    html += "</tr>"
                }
                html += "</tbody></table></div>"
            }
            html += "</div>"
        }
        return html
    }

    static func compileSampleTableHTML(result: AnalysisResult, includeTable: Bool) -> String {
        guard includeTable, let fp = result.fullPreview else { return "" }
        var html = "<div class='card page-break' style='break-inside: avoid;'>"
        html += "<div class='card-title'>🗃️ Dataset Preview (First 50 Rows)</div>"
        html += "<div class='table-wrapper'><table>"
        html += "<thead><tr>"
        for col in fp.columns {
            html += "<th>\(col)</th>"
        }
        html += "</tr></thead><tbody>"
        for row in fp.rows.prefix(50) {
            html += "<tr>"
            for val in row {
                html += "<td>\(val)</td>"
            }
            html += "</tr>"
        }
        html += "</tbody></table></div>"
        html += "</div>"
        return html
    }
}
